name: Unit Tests

on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependency
        run: pip install pytest

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest